### ISSUE TITLE
More TO-DO'S

### ISSUE THREAD

**Issue by AmirulAndalib** [yash-dk/TorToolkit-Telegram#112]
# Some more stuff to Make tortoolkit more dynamic and should be implemented

- [ ] **Add Rclone Server Side Copy or called as Google Drive File/Folder Clone .**
- [ ] **Move Clients and other stuf from main.py to init.py in tortoolkit folder so that we can add modules easily .**
- [ ] **make a folder named modules and move modules like speedtest to there and future extra modules .**
- [ ] **Make a permanent fix for QBT file Selection .**
- [ ] **Remove Dependencies on requirements.txt .**
- [ ] **Add QBT search with module .**
- [ ] **Change YTDL engine to YT-DLP cuz yt-dl dead .....YT-DLP is very fast smooth maintained and updated everyday .**
- [ ]  **Add Numbering List Instead of using `🚩` like '1, 2, 3, 4' in telegram file leech results**
- [ ]  **Download Telegram files and Upload to cloud .**
- [ ]  Fix Bug **This torrent is already in the leech list...Even When Torrent Is Different...**  **F.Y.I: https://t.me/ttkdisc/27428**
